### ISSUE TITLE
don't hard code tokens and passwords 

### ISSUE THREAD

**Issue by yoosuf** [ECLK/auth-app#5]
the values are hard coded on routes/auth.js, which is not right way to code when doing open source apps  
`
 id: 'Bc9am2voec_NAvfJA8KmpiZ0qAca',
 secret: 'hD3_9rDl6Khkb6uYd7vKmnc9ThYa'
`

**Comment by YujithIsura** [comment]
Hi Yoosuf,
auth-app serves internally when we do it in the production environment. So
this is just temporary id and secret.
Thanks for your response. :)

**Comment by yoosuf** [comment]
you guys better hire me to do code reviews before committing //cc @sanjiva
